# Generated by Django 4.0.6 on 2022-07-22 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment_tv",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment_movie",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Movies.movie"
            ),
        ),
        migrations.AddField(
            model_name="comment_movie",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="comment_tv",
            index=models.Index(
                fields=["user", "tv"], name="Movies_comm_user_id_997f47_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="comment_tv",
            unique_together={("user", "tv")},
        ),
        migrations.AddIndex(
            model_name="comment_movie",
            index=models.Index(
                fields=["user", "movie"], name="Movies_comm_user_id_6ff203_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="comment_movie",
            unique_together={("user", "movie")},
        ),
    ]
