# Generated by Django 4.0.6 on 2022-08-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvandmovie',
            name='tmdb_id',
            field=models.IntegerField(verbose_name=''),
        ),
    ]
