# Generated by Django 4.0.6 on 2022-08-17 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Movies", "0003_alter_tvandmovie_tmdb_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LikeForComment_movie",
            new_name="LikeForComment",
        ),
        migrations.RenameModel(
            old_name="LikeForMovie",
            new_name="LikeForMovieAndTV",
        ),
        migrations.RenameModel(
            old_name="WantToSeeMovie",
            new_name="WantToSeeMovieAndTV",
        ),
    ]
